version: '3.8'

volumes:
  data_database:

services:
  app:
    build:
      context: .
      target: dev
      # args:
      #   NOVA_USERNAME: ${NOVA_USERNAME:-webmaster@centerforceit.com.au}
      #   NOVA_LICENSE_KEY: ${NOVA_LICENSE_KEY:?err}
    container_name: app
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8
    container_name: ${DB_HOST:-database}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
       - 'data_database:/var/lib/mysql/'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-database}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-laravel}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: ${DB_HOST:-database}
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME:-laravel}
      PMA_PASSWORD: ${DB_PASSWORD:-laravel}
      UPLOAD_LIMIT: 1G
    ports:
      - 9001:80

  mailhog:
    image: mailhog/mailhog
    ports:
      - 9002:8025
    logging:
      driver: 'none'  # disable saving logs
